apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: send-legal-mail-to-prisons
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/custom-http-errors: "418"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.internalHost }}
    secretName: {{ .Values.ingress.internalCertSecret }}
  rules:
  - host: {{ .Values.ingress.internalHost }}
    http:
      paths:
        - path: /
          backend:
            serviceName: send-legal-mail-to-prisons
            servicePort: http
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: check-rule39-mail
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/custom-http-errors: "418"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      location = / {
        return 301 $scheme://$host/barcode/find-recipient;
      }
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.externalHost }}
      secretName: {{ .Values.ingress.externalCertSecret }}
  rules:
    - host: {{ .Values.ingress.externalHost }}
      http:
        paths:
            - path: /
              backend:
                serviceName: send-legal-mail-to-prisons
                servicePort: http
