version: '3.1'
services:

  redis:
    image: 'bitnami/redis:5.0'
    networks:
      - hmpps_int
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

  wiremock:
    image: wiremock/wiremock
    networks:
    - hmpps_int
    container_name: wiremock
    ports:
      - "9091:8080"

  gotenberg:
    image: thecodingmachine/gotenberg:6.4.4
    networks:
      - hmpps_int
    container_name: gotenberg
    ports:
      - "3001:3000"
    environment:
      - GOOGLE_CHROME_IGNORE_CERTIFICATE_ERRORS=1
      - DISABLE_UNOCONV=1
      - DEFAULT_WAIT_TIMEOUT=30
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3000/ping' ]

networks:
  hmpps_int:
