kind: Service
apiVersion: v1
metadata:
  name: maintenance-page-slm-svc
  labels:
    app: maintenance-page-slm-svc
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  selector:
    app: maintenance-page-slm
