/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/link/verify': {
    /** Verifies a magic link secret and swaps it for an authentication token if valid. */
    post: operations['verifyMagicLink']
  }
  '/link/email': {
    /** Creates a magic link and send to the email address entered by the user. */
    post: operations['createMagicLink']
  }
  '/barcode': {
    post: operations['createBarcode']
  }
  '/barcode/check': {
    post: operations['checkBarcode']
  }
}

export interface components {
  schemas: {
    VerifyLinkRequest: {
      /** The secret to verify */
      secret: string
    }
    VerifyLinkResponse: {
      /** The JWT */
      token: string
    }
    ErrorCode: {
      code: string
      userMessage: string
    }
    ErrorResponse: {
      status: number
      errorCode: components['schemas']['ErrorCode']
    }
    MagicLinkRequest: {
      /** The email address to send the magic link to */
      email: string
    }
    CheckBarcodeRequest: {
      /** The barcode being checked */
      barcode: string
    }
  }
}

export interface operations {
  /** Verifies a magic link secret and swaps it for an authentication token if valid. */
  verifyMagicLink: {
    responses: {
      /** Authentication token created */
      201: {
        content: {
          'application/json': components['schemas']['VerifyLinkResponse']
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Not found, unable to verify the magic link */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['VerifyLinkRequest']
      }
    }
  }
  /** Creates a magic link and send to the email address entered by the user. */
  createMagicLink: {
    responses: {
      /** Magic link created */
      201: {
        content: {
          'application/json': unknown
        }
      }
      /** Unauthorised, requires a valid Oauth2 token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MagicLinkRequest']
      }
    }
  }
  createBarcode: {
    responses: {
      /** Barcode created */
      201: {
        content: {
          'application/json': string
        }
      }
      /** Bad request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid magic link token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  checkBarcode: {
    responses: {
      /** Barcode is OK and no further checks are required */
      200: {
        content: {
          'application/json': unknown
        }
      }
      /** Bad request */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Unauthorised, requires a valid magic link token */
      401: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Not found */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CheckBarcodeRequest']
      }
    }
  }
}
