/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/secure/prisons/id/{prisonId}/videolink-conferencing-centre/email-address': {
    get: operations['getEmailForVideoConferencingCentre']
    put: operations['putEmailAddressForVideolinkConferencingCentre']
    delete: operations['deleteEmailAddressForVideolinkConferencingCentre']
  }
  '/secure/prisons/id/{prisonId}/offender-management-unit/email-address': {
    get: operations['getEmailForOffenderManagementUnit']
    put: operations['putEmailAddressForOffenderManagementUnit']
    delete: operations['deleteEmailAddressForOffenderManagementUnit']
  }
  '/prisons': {
    /** All prisons */
    get: operations['getPrisons']
  }
  '/prisons/id/{prisonId}': {
    /** Information on a specific prison */
    get: operations['getPrisonFromId']
  }
  '/gp/prison/{prisonId}': {
    get: operations['getGpPrescriberFromPrisonId']
  }
  '/gp/practice/{gpPracticeCode}': {
    get: operations['getPrisonFromGpPrescriber']
  }
}

export interface components {
  schemas: {
    /** Prison Information */
    PrisonDto: {
      /** Prison ID */
      prisonId: string
      /** Name of the prison */
      prisonName: string
      /** Whether the prison is still active */
      active: boolean
    }
    ErrorResponse: {
      status: number
      errorCode?: number
      userMessage?: string
      developerMessage?: string
      moreInfo?: string
    }
  }
}

export interface operations {
  getEmailForVideoConferencingCentre: {
    parameters: {
      path: {
        prisonId: string
      }
    }
    responses: {
      /** Returns the email address */
      200: {
        content: {
          'text/plain': unknown
        }
      }
      /** Client error - invalid prisonId or similar */
      400: {
        content: {
          'text/plain': string
        }
      }
      /** The prison does not have a Videolink Conferencing Centre email address */
      404: {
        content: {
          'text/plain': string
        }
      }
    }
  }
  putEmailAddressForVideolinkConferencingCentre: {
    parameters: {
      path: {
        prisonId: string
      }
    }
    responses: {
      /** The email address was created */
      201: unknown
      /** The email address was updated */
      204: never
      /** Client error - invalid prisonId, email address or similar */
      400: unknown
      /** No prison found for the supplied prison id */
      404: unknown
    }
    requestBody: {
      content: {
        'text/plain': string
      }
    }
  }
  deleteEmailAddressForVideolinkConferencingCentre: {
    parameters: {
      path: {
        prisonId: string
      }
    }
    responses: {
      /** The email address was removed */
      204: never
      /** Client error - invalid prisonId or similar */
      400: unknown
    }
  }
  getEmailForOffenderManagementUnit: {
    parameters: {
      path: {
        prisonId: string
      }
    }
    responses: {
      /** Returns the email address */
      200: {
        content: {
          'text/plain': unknown
        }
      }
      /** Client error - invalid prisonId or similar */
      400: {
        content: {
          'text/plain': string
        }
      }
      /** The prison does not have a Offender Management Unit email address */
      404: {
        content: {
          'text/plain': string
        }
      }
    }
  }
  putEmailAddressForOffenderManagementUnit: {
    parameters: {
      path: {
        prisonId: string
      }
    }
    responses: {
      /** The email address was created */
      201: unknown
      /** The email address was updated */
      204: never
      /** Client error - invalid prisonId, email address, media type or similar */
      400: unknown
      /** No prison found for the supplied prison id */
      404: unknown
    }
    requestBody: {
      content: {
        'text/plain': string
      }
    }
  }
  deleteEmailAddressForOffenderManagementUnit: {
    parameters: {
      path: {
        prisonId: string
      }
    }
    responses: {
      /** The email address was removed */
      204: never
      /** Client error - invalid prisonId or similar */
      400: unknown
    }
  }
  /** All prisons */
  getPrisons: {
    responses: {
      /** Successful Operation */
      200: {
        content: {
          'application/json': unknown
        }
      }
    }
  }
  /** Information on a specific prison */
  getPrisonFromId: {
    parameters: {
      path: {
        prisonId: string
      }
    }
    responses: {
      /** Successful Operation */
      200: {
        content: {
          'application/json': components['schemas']['PrisonDto']
        }
      }
    }
  }
  getGpPrescriberFromPrisonId: {
    parameters: {
      path: {
        /** Prison ID */
        prisonId: string
      }
    }
    responses: {
      /** Bad request.  Wrong format for prison_id. */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** Prison not found. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
  getPrisonFromGpPrescriber: {
    parameters: {
      path: {
        /** GP Practice Code */
        gpPracticeCode: string
      }
    }
    responses: {
      /** Bad request.  Wrong format for GP practice code. */
      400: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
      /** No prison linked to the GP practice code. */
      404: {
        content: {
          'application/json': components['schemas']['ErrorResponse']
        }
      }
    }
  }
}
