---
# Per environment values which override defaults in send-legal-mail-to-prisons/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: send-legal-mail.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://send-legal-mail.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    SEND_LEGAL_MAIL_API_URL: "https://send-legal-mail-api.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register.hmpps.service.justice.gov.uk"
    ONE_TIME_CODE_AUTH_ENABLED: "true"

generic-prometheus-alerts:
  alertSeverity: send-legal-mail-alerts
