# Per environment values which override defaults in send-legal-mail-to-prisons/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: send-legal-mail-dev.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://send-legal-mail-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SEND_LEGAL_MAIL_API_URL: "https://send-legal-mail-api-dev.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-dev.hmpps.service.justice.gov.uk"
    COVERSHEET_PRINT_DEBUG: "true"
    LSJ_SESSION_DURATION_IN_DAYS: 1
    ONE_TIME_CODE_AUTH_ENABLED: "true"

  namespace_secrets:
    smoke-test:
      APP_SMOKETEST_MSJSECRET: "APP_SMOKETEST_MSJSECRET"
      APP_SMOKETEST_LSJSECRET: "APP_SMOKETEST_LSJSECRET"

  allowlist:
    moj-official-tgw-prod: 51.149.250.0/24
    circleci-1: 3.228.39.90/32
    circleci-2: 18.213.67.41/32
    circleci-3: 34.194.94.201/32
    circleci-4: 34.194.144.202/32
    circleci-5: 34.197.6.234/32
    circleci-6: 35.169.17.173/32
    circleci-7: 35.174.253.146/32
    circleci-8: 52.3.128.216/32
    circleci-9: 52.4.195.249/32
    circleci-10: 52.5.58.121/32
    circleci-11: 52.21.153.129/32
    circleci-12: 52.72.72.233/32
    circleci-13: 54.92.235.88/32
    circleci-14: 54.161.182.76/32
    circleci-15: 54.164.161.41/32
    circleci-16: 54.166.105.113/32
    circleci-17: 54.167.72.230/32
    circleci-18: 54.172.26.132/32
    circleci-19: 54.205.138.102/32
    circleci-20: 54.208.72.234/32
    circleci-21: 54.209.115.53/32
    groups:
      - internal

gotenberg:
  replicaCount: 2

generic-prometheus-alerts:
  alertSeverity: send-legal-mail-alerts
