# Per environment values which override defaults in send-legal-mail-to-prisons/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: send-legal-mail-preprod.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://send-legal-mail-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    SEND_LEGAL_MAIL_API_URL: "https://send-legal-mail-api-preprod.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-preprod.hmpps.service.justice.gov.uk"
    ONE_TIME_CODE_AUTH_ENABLED: "true"

  namespace_secrets:
    smoke-test:
      APP_SMOKETEST_MSJSECRET: "APP_SMOKETEST_MSJSECRET"
      APP_SMOKETEST_LSJSECRET: "APP_SMOKETEST_LSJSECRET"

  allowlist:
    moj-official-tgw-prod: 51.149.250.0/24
    groups:
      - internal
      - circleci

generic-prometheus-alerts:
  alertSeverity: hmpps-visits-send-legal-email-preprod
