---
# Per environment values which override defaults in send-legal-mail-to-prisons/values.yaml

generic-service:
  replicaCount: 2

  env:
    INGRESS_URL: "https://check-rule39-mail-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    SEND_LEGAL_MAIL_API_URL: "https://send-legal-mail-api-preprod.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-preprod.hmpps.service.justice.gov.uk"
    ONE_TIME_CODE_AUTH_ENABLED: "true"

  namespace_secrets:
    smoke-test:
      APP_SMOKETEST_MSJSECRET: "APP_SMOKETEST_MSJSECRET"
      APP_SMOKETEST_LSJSECRET: "APP_SMOKETEST_LSJSECRET"

allowlist:
  office: "217.33.148.210/32"
  health-kick: "35.177.252.195/32"
  petty-france-wifi: "213.121.161.112/28"
  global-protect: "35.176.93.186/32"
  mojvpn: "81.134.202.29/32"
  cloudplatform-live1-1: "35.178.209.113/32"
  cloudplatform-live1-2: "3.8.51.207/32"
  cloudplatform-live1-3: "35.177.252.54/32"

generic-prometheus-alerts:
  alertSeverity: farsight-alerts

ingress:
  internalHost: check-rule39-mail-preprod.prison.service.justice.gov.uk
  externalHost: send-legal-mail-preprod.prison.service.justice.gov.uk
  internalSetIdentifier: check-rule39-mail-send-legal-mail-to-prisons-preprod-green
  externalSetIdentifier: send-legal-mail-to-prisons-send-legal-mail-to-prisons-preprod-green
