# Per environment values which override defaults in send-legal-mail-to-prisons/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: send-legal-mail-dev.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://send-legal-mail-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    SEND_LEGAL_MAIL_API_URL: "https://send-legal-mail-api-dev.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-dev.hmpps.service.justice.gov.uk"
    COVERSHEET_PRINT_DEBUG: "true"
    LSJ_SESSION_DURATION_IN_DAYS: 1
    ONE_TIME_CODE_AUTH_ENABLED: "true"
    ENVIRONMENT_NAME: dev

  namespace_secrets:
    smoke-test:
      APP_SMOKETEST_MSJSECRET: "APP_SMOKETEST_MSJSECRET"
      APP_SMOKETEST_LSJSECRET: "APP_SMOKETEST_LSJSECRET"

  allowlist:
    moj-official-tgw-prod: 51.149.250.0/24
    groups:
      - internal

gotenberg:
  replicaCount: 2

generic-prometheus-alerts:
  alertSeverity: hmpps-visits-send-legal-email-dev
