---
# Per environment values which override defaults in send-legal-mail-to-prisons/values.yaml

generic-service:
  replicaCount: 2

  env:
    INGRESS_URL: "https://check-rule39-mail-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SEND_LEGAL_MAIL_API_URL: "https://send-legal-mail-api-dev.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-dev.hmpps.service.justice.gov.uk"
    SUPPORTED_PRISONS: ""
    COVERSHEET_PRINT_DEBUG: "true"

  namespace_secrets:
    smoke-test:
      APP_SMOKETEST_MSJSECRET: "APP_SMOKETEST_MSJSECRET"
      APP_SMOKETEST_LSJSECRET: "APP_SMOKETEST_LSJSECRET"

gotenberg:
  replicaCount: 1

generic-prometheus-alerts:
  alertSeverity: farsight-alerts

ingress:
  internalHost: check-rule39-mail-dev.prison.service.justice.gov.uk
  externalHost: send-legal-mail-dev.prison.service.justice.gov.uk
  internalSetIdentifier: check-rule39-mail-send-legal-mail-to-prisons-dev-green
  externalSetIdentifier: send-legal-mail-to-prisons-send-legal-mail-to-prisons-dev-green