---
# Per environment values which override defaults in send-legal-mail-to-prisons/values.yaml

generic-service:
  replicaCount: 2

  env:
    INGRESS_URL: "https://check_rule39-mail-preprod.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-preprod.prison.service.justice.gov.uk"
    SEND_LEGAL_MAIL_API_URL: "https://send-legal-mail-api-preprod.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-preprod.hmpps.service.justice.gov.uk"
    SUPPORTED_PRISONS: "SKI"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

ingress:
  internalHost: check-rule39-mail-preprod.prison.service.justice.gov.uk
  externalHost: send-legal-mail-preprod.prison.service.justice.gov.uk
