---
# Per environment values which override defaults in send-legal-mail-to-prisons/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: check-rule39-mail-dev.prison.service.justice.gov.uk

  env:
    INGRESS_URL: "https://check-rule39-mail-dev.prison.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    SEND_LEGAL_MAIL_API_URL: "https://send-legal-mail-api-dev.prison.service.justice.gov.uk"
    PRISON_REGISTER_API_URL: "https://prison-register-dev.hmpps.service.justice.gov.uk"
    COVERSHEET_PRINT_DEBUG: "true"
    LSJ_SESSION_DURATION_IN_DAYS: 1
    ONE_TIME_CODE_AUTH_ENABLED: "true"

  namespace_secrets:
    smoke-test:
      APP_SMOKETEST_MSJSECRET: "APP_SMOKETEST_MSJSECRET"
      APP_SMOKETEST_LSJSECRET: "APP_SMOKETEST_LSJSECRET"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    # Circle CI allowed for smoke tests. IP ranges defined here: https://circleci.com/docs/2.0/ip-ranges#list-of-ip-address-ranges
    circle-ci-1: "3.228.39.90"
    circle-ci-2: "18.213.67.41"
    circle-ci-3: "34.194.94.201"
    circle-ci-4: "34.194.144.202"
    circle-ci-5: "34.197.6.234"
    circle-ci-6: "35.169.17.173"
    circle-ci-7: "35.174.253.146"
    circle-ci-8: "52.3.128.216"
    circle-ci-9: "52.4.195.249"
    circle-ci-10: "52.5.58.121"
    circle-ci-11: "52.21.153.129"
    circle-ci-12: "52.72.72.233"
    circle-ci-13: "54.92.235.88"
    circle-ci-14: "54.161.182.76"
    circle-ci-15: "54.164.161.41"
    circle-ci-16: "54.166.105.113"
    circle-ci-17: "54.167.72.230"
    circle-ci-18: "54.172.26.132"
    circle-ci-19: "54.205.138.102"
    circle-ci-20: "54.208.72.234"
    circle-ci-21: "54.209.115.53"


gotenberg:
  replicaCount: 2

generic-prometheus-alerts:
  alertSeverity: send-legal-mail-alerts
